### ISSUE TITLE
Support for wrapfig feature

### ISSUE THREAD

**Issue by Migacz85** [maehr/academic-pandoc-template#31]
There is a package wrap fig. It's nice to have possibility to put figure on right left and be wrapped with the text.

Here is some filter that I found for Pandoc:

https://github.com/scotthartley/pandoc-wrapfig/blob/master/pandoc-wrapfig.py

**Comment by maehr** [comment]
Hi @Migacz85 

Thank you for opening an issue. I don not plan to integrate this filter, but I will gladly add a link to your fork if you do.

Best
Moritz
